# Generated by Django 5.2.7 on 2025-11-02 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionextra',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatextra',
            name='inscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='extras.inscriptionextra'),
        ),
        migrations.AddField(
            model_name='moduleextra',
            name='formation_extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.formationextra'),
        ),
        migrations.AddField(
            model_name='paiementextra',
            name='inscription_extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extras.inscriptionextra'),
        ),
    ]
