# Generated by Django 4.2.26 on 2025-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementextra',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire')], default='virement', max_length=20),
        ),
        migrations.AddField(
            model_name='paiementextra',
            name='reference_paiement',
            field=models.CharField(blank=True, help_text='Référence du paiement (numéro de transaction, etc.)', max_length=100, null=True),
        ),
    ]
