# Generated by Django 4.2.26 on 2025-11-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_paiementextra_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementextra',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('bancaire', 'Virement bancaire'), ('orange_money', 'Orange Money')], default='bancaire', max_length=20),
        ),
    ]
