# Generated by Django 4.2.26 on 2025-11-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0043_comptebancaire_paiementformation_compte_bancaire'),
        ('extras', '0004_alter_paiementextra_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementextra',
            name='compte_bancaire',
            field=models.ForeignKey(blank=True, help_text='Compte bancaire sur lequel le paiement a été effectué (si mode bancaire)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_extra', to='utilisateurs.comptebancaire', verbose_name='Compte bancaire'),
        ),
    ]
