# Generated by Django 4.2.25 on 2025-11-17 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='message',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='communications.message', verbose_name='Message parent'),
        ),
        migrations.AddField(
            model_name='message',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='messages/pieces_jointes/', verbose_name='Pièce jointe'),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime_par_destinataire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='supprime_par_expediteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='message',
            name='lu',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(max_length=200, verbose_name='Sujet'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['destinataire', 'lu'], name='communicati_destina_e61270_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['expediteur', 'date_envoi'], name='communicati_expedit_b37fe4_idx'),
        ),
    ]
