# Generated by Django 4.2.26 on 2025-11-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_classe_competence_cours_formation_jalonprogramme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='membre_coordination',
            field=models.BooleanField(default=False, help_text='Accès au menu Administration pour gérer les formations, agenda, notes, etc.', verbose_name='Membre de la coordination DESMFMC'),
        ),
    ]
