# Generated by Django 4.2.26 on 2025-11-11 18:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_seed_des_planifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSComUCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du CSCom-U')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code du CSCom-U')),
                ('type_centre', models.CharField(choices=[('urbain', 'Urbain'), ('rural', 'Rural')], default='urbain', max_length=10, verbose_name='Type de CSCom-U')),
                ('localisation', models.CharField(blank=True, max_length=150, verbose_name='Localisation / Commune')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif pour les affectations')),
            ],
            options={
                'verbose_name': 'CSCom-U',
                'verbose_name_plural': 'CSCom-U',
                'ordering': ['type_centre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateur'},
        ),
        migrations.CreateModel(
            name='StageRotationDES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(3)], verbose_name='Année du DES (2 ou 3)')),
                ('periode', models.IntegerField(choices=[(1, 'Période 1 (janvier-avril)'), (2, 'Période 2 (mai-août)')], verbose_name='Période de stage')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('attribue_automatiquement', models.BooleanField(default=False, verbose_name='Tirage automatique')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire / ajustements')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages_attribues', to='utilisateurs.cscomucentre', verbose_name='CSCom-U attribué')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='stages_rotation_des', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Stage CSCom-U',
                'verbose_name_plural': 'Stages CSCom-U',
                'ordering': ['annee', 'periode', 'etudiant__username'],
                'unique_together': {('etudiant', 'annee', 'periode'), ('etudiant', 'centre')},
            },
        ),
        migrations.CreateModel(
            name='StagePremiereAnnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('medecine_interne', 'Médecine interne'), ('chirurgie', 'Chirurgie générale'), ('pediatrie', 'Pédiatrie'), ('gynecologie', 'Gynécologie-obstétrique'), ('psychiatrie', 'Psychiatrie'), ('autre', 'Autre service')], max_length=30, verbose_name='Service hospitalier')),
                ('service_autre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Autre service (si autre)')),
                ('hopital', models.CharField(max_length=200, verbose_name='Hôpital / Centre hospitalier')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('valide', models.BooleanField(default=False, verbose_name='Stage validé')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note du stage (sur 20)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire / Appréciation')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='stages_premiere_annee', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('responsable_stage', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_supervises', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du stage')),
            ],
            options={
                'verbose_name': 'Stage 1ère année',
                'verbose_name_plural': 'Stages 1ère année',
                'ordering': ['etudiant', 'date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MemoireFinEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre du mémoire')),
                ('structure_accueil', models.CharField(max_length=300, verbose_name="Structure d'accueil")),
                ('structure_autre', models.CharField(blank=True, max_length=300, null=True, verbose_name='Autre structure (si acceptée par coordination)')),
                ('accepte_par_coordination', models.BooleanField(default=False, verbose_name='Structure acceptée par la coordination')),
                ('date_debut_memoire', models.DateField(blank=True, null=True, verbose_name='Date de début du mémoire')),
                ('date_soumission', models.DateField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_soutenance', models.DateField(blank=True, null=True, verbose_name='Date de soutenance')),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('soumis', 'Soumis à la coordination'), ('en_evaluation', 'En évaluation'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('soutenu', 'Soutenu'), ('valide', 'Validé')], default='en_preparation', max_length=20, verbose_name='Statut')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note du mémoire (sur 20)')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé du mémoire')),
                ('mots_cles', models.CharField(blank=True, max_length=300, verbose_name='Mots-clés')),
                ('commentaires_coordination', models.TextField(blank=True, verbose_name='Commentaires de la coordination')),
                ('fichier_memoire', models.FileField(blank=True, null=True, upload_to='memoires/', verbose_name='Fichier du mémoire')),
                ('cscom_choisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires', to='utilisateurs.cscomucentre', verbose_name='CSCom-U choisi (si applicable)')),
                ('directeur_memoire', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Directeur de mémoire')),
                ('etudiant', models.OneToOneField(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='memoire_fin_etude', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': "Mémoire de fin d'étude",
                'verbose_name_plural': "Mémoires de fin d'étude",
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='ResultatAnneeDES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Année du DES (1 à 4)')),
                ('cours_theoriques_valides', models.BooleanField(default=False, verbose_name='Cours théoriques validés')),
                ('presence_validee', models.BooleanField(default=False, verbose_name='Présence aux enseignements validée')),
                ('stages_valides', models.BooleanField(default=False, verbose_name='Stages hospitaliers validés')),
                ('note_theorique', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note théorique (sur 20)')),
                ('note_pratique', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note pratique (sur 20)')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=4, null=True, verbose_name='Moyenne générale (sur 20)')),
                ('epreuve_malade_validee', models.BooleanField(default=False, verbose_name='Épreuve du malade validée')),
                ('evaluations_finales_validees', models.BooleanField(default=False, verbose_name='Évaluations finales validées')),
                ('memoire_titre', models.CharField(blank=True, max_length=255, verbose_name='Titre du mémoire')),
                ('memoire_structure', models.CharField(blank=True, max_length=255, verbose_name="Structure d'accueil du mémoire")),
                ('memoire_valide', models.BooleanField(default=False, verbose_name='Mémoire soutenu et validé')),
                ('memoire_date_soutenance', models.DateField(blank=True, null=True, verbose_name='Date de soutenance')),
                ('decision', models.CharField(choices=[('en_cours', 'Évaluation en cours'), ('admis', 'Admis en année suivante'), ('ajourne', 'Ajourné'), ('diplome', 'Diplômé')], default='en_cours', max_length=20, verbose_name='Décision')),
                ('decision_forcee', models.BooleanField(default=False, verbose_name='Décision forcée manuellement')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_des', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_des', to='utilisateurs.formation', verbose_name='Formation')),
                ('stage_rural', models.ForeignKey(blank=True, limit_choices_to={'centre__type_centre': 'rural'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_ruraux', to='utilisateurs.stagerotationdes', verbose_name='Stage rural')),
                ('stage_urbain', models.ForeignKey(blank=True, limit_choices_to={'centre__type_centre': 'urbain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_urbains', to='utilisateurs.stagerotationdes', verbose_name='Stage urbain')),
            ],
            options={
                'verbose_name': 'Résultat annuel DES',
                'verbose_name_plural': 'Résultats annuels DES',
                'ordering': ['etudiant__username', 'annee'],
                'unique_together': {('etudiant', 'formation', 'annee')},
            },
        ),
    ]
