# Generated by Django 4.2.26 on 2025-11-11 18:21

from django.db import migrations


def seed_cscom_u(apps, schema_editor):
    """Ajoute les CSCom-U urbains et ruraux du DESMFMC"""
    CSComUCentre = apps.get_model('utilisateurs', 'CSComUCentre')
    
    # CSCom-U Urbains
    cscom_urbains = [
        {
            'nom': 'CSCom-U de Banconi',
            'code': 'CSCOM-U-BANCONI',
            'type_centre': 'urbain',
            'localisation': 'Banconi',
        },
        {
            'nom': 'CSCom-U de Kayes N\'di',
            'code': 'CSCOM-U-KAYES-NDI',
            'type_centre': 'urbain',
            'localisation': 'Kayes N\'di',
        },
        {
            'nom': 'CSCom-U de Sanoubougou 2',
            'code': 'CSCOM-U-SANOUBOUGOU-2',
            'type_centre': 'urbain',
            'localisation': 'Sanoubougou 2',
        },
    ]
    
    # CSCom-U Ruraux
    cscom_ruraux = [
        {
            'nom': 'CSCom-U de Ségué',
            'code': 'CSCOM-U-SEGUE',
            'type_centre': 'rural',
            'localisation': 'Ségué',
        },
        {
            'nom': 'CSCom-U de Kononbougou',
            'code': 'CSCOM-U-KONONBOUGOU',
            'type_centre': 'rural',
            'localisation': 'Kononbougou',
        },
        {
            'nom': 'CSCom-U de Sanakoroba',
            'code': 'CSCOM-U-SANAKOROBA',
            'type_centre': 'rural',
            'localisation': 'Sanakoroba',
        },
        {
            'nom': 'CSCom-U de Koniakary',
            'code': 'CSCOM-U-KONIAKARY',
            'type_centre': 'rural',
            'localisation': 'Koniakary',
        },
    ]
    
    # Créer les CSCom-U urbains
    for cscom_data in cscom_urbains:
        CSComUCentre.objects.get_or_create(
            code=cscom_data['code'],
            defaults={
                'nom': cscom_data['nom'],
                'type_centre': cscom_data['type_centre'],
                'localisation': cscom_data['localisation'],
                'actif': True,
            }
        )
    
    # Créer les CSCom-U ruraux
    for cscom_data in cscom_ruraux:
        CSComUCentre.objects.get_or_create(
            code=cscom_data['code'],
            defaults={
                'nom': cscom_data['nom'],
                'type_centre': cscom_data['type_centre'],
                'localisation': cscom_data['localisation'],
                'actif': True,
            }
        )


def unseed_cscom_u(apps, schema_editor):
    """Supprime les CSCom-U créés"""
    CSComUCentre = apps.get_model('utilisateurs', 'CSComUCentre')
    
    codes_a_supprimer = [
        'CSCOM-U-BANCONI',
        'CSCOM-U-KAYES-NDI',
        'CSCOM-U-SANOUBOUGOU-2',
        'CSCOM-U-SEGUE',
        'CSCOM-U-KONONBOUGOU',
        'CSCOM-U-SANAKOROBA',
        'CSCOM-U-KONIAKARY',
    ]
    
    CSComUCentre.objects.filter(code__in=codes_a_supprimer).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_cscomucentre_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_cscom_u, unseed_cscom_u),
    ]
