# Generated by Django 4.2.26 on 2025-11-12 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_seed_cours_lecons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la leçon')),
                ('numero', models.IntegerField(default=1, help_text="Numéro d'ordre dans le cours", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numéro de la leçon')),
                ('type_lecon', models.CharField(choices=[('lecon', 'Leçon'), ('atelier', 'Atelier'), ('tp', 'Travaux pratiques'), ('td', 'Travaux dirigés')], default='lecon', max_length=20, verbose_name='Type de leçon')),
                ('contenu', models.TextField(blank=True, help_text='Contenu textuel de la leçon', null=True, verbose_name='Contenu de la leçon')),
                ('fichier_contenu', models.FileField(blank=True, help_text='Fichier PDF, Word, PowerPoint, etc. contenant le contenu de la leçon', null=True, upload_to='cours/lecons/', verbose_name='Fichier de contenu')),
                ('duree_estimee', models.IntegerField(default=0, help_text='Durée estimée pour compléter cette leçon', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durée estimée (minutes)')),
                ('ressources', models.TextField(blank=True, help_text='Liens, références, documents supplémentaires', null=True, verbose_name='Ressources complémentaires')),
                ('ordre', models.IntegerField(default=0, help_text='Ordre dans le cours (utilisé pour trier les leçons)', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='utilisateurs.cours', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['cours', 'ordre', 'numero'],
                'unique_together': {('cours', 'numero')},
            },
        ),
    ]
