# Generated by Django 4.2.26 on 2025-11-12 10:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_clean_cours_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enonce', models.TextField(verbose_name='Énoncé de la question')),
                ('type_reponse', models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('texte_libre', 'Texte libre'), ('vrai_faux', 'Vrai/Faux')], default='choix_unique', max_length=20, verbose_name='Type de réponse')),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('explication', models.TextField(blank=True, help_text='Affichée après la correction', null=True, verbose_name='Explication de la réponse')),
            ],
            options={
                'verbose_name': 'Question de quiz',
                'verbose_name_plural': 'Questions de quiz',
                'ordering': ['quiz', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='QuizLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du quiz/exercice')),
                ('type_quiz', models.CharField(choices=[('quiz', 'Quiz'), ('exercice', 'Exercice'), ('evaluation', 'Évaluation')], default='quiz', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('instructions', models.TextField(help_text='Instructions pour compléter le quiz/exercice', verbose_name='Instructions')),
                ('duree_minutes', models.IntegerField(default=0, help_text='0 = pas de limite de temps', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Durée estimée (minutes)')),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note maximale')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='utilisateurs.lecon', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Quiz/Exercice de leçon',
                'verbose_name_plural': 'Quiz/Exercices de leçons',
                'ordering': ['lecon', 'ordre', 'date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=500, verbose_name='Texte de la réponse')),
                ('est_correcte', models.BooleanField(default=False, verbose_name='Est correcte')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_possibles', to='utilisateurs.questionquiz', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse possible',
                'verbose_name_plural': 'Réponses possibles',
                'ordering': ['question', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='questionquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='utilisateurs.quizlecon', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='CommentaireLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu du commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_lecons', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='utilisateurs.lecon', verbose_name='Leçon')),
                ('parent', models.ForeignKey(blank=True, help_text='Pour les réponses aux commentaires', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='utilisateurs.commentairelecon', verbose_name='Commentaire parent')),
            ],
            options={
                'verbose_name': 'Commentaire de leçon',
                'verbose_name_plural': 'Commentaires de leçons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ResultatQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_finale', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note finale')),
                ('pourcentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('termine', models.BooleanField(default=False, verbose_name='Terminé')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='utilisateurs.quizlecon', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Résultat de quiz',
                'verbose_name_plural': 'Résultats de quiz',
                'ordering': ['-date_creation'],
                'unique_together': {('etudiant', 'quiz')},
            },
        ),
        migrations.CreateModel(
            name='ReponseEtudiantQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_texte', models.TextField(blank=True, null=True, verbose_name='Réponse texte (pour texte libre)')),
                ('points_obtenus', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points obtenus')),
                ('date_reponse', models.DateTimeField(auto_now_add=True, verbose_name='Date de réponse')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='reponses_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_etudiants', to='utilisateurs.questionquiz', verbose_name='Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_etudiants', to='utilisateurs.quizlecon', verbose_name='Quiz')),
                ('reponses_choisies', models.ManyToManyField(blank=True, to='utilisateurs.reponsequestion', verbose_name='Réponses choisies (pour choix multiple/unique)')),
            ],
            options={
                'verbose_name': "Réponse d'étudiant",
                'verbose_name_plural': "Réponses d'étudiants",
                'ordering': ['-date_reponse'],
                'unique_together': {('etudiant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('valide', 'Validé')], default='non_commence', max_length=20, verbose_name='Statut')),
                ('pourcentage_completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de complétion')),
                ('temps_passe_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Temps passé (minutes)')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('notes', models.TextField(blank=True, help_text="Notes que l'étudiant peut prendre sur cette leçon", null=True, verbose_name='Notes personnelles')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='utilisateurs.lecon', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Progression de leçon',
                'verbose_name_plural': 'Progressions de leçons',
                'ordering': ['lecon__ordre', 'lecon__numero'],
                'unique_together': {('etudiant', 'lecon')},
            },
        ),
    ]
