# Generated by Django 4.2.26 on 2025-11-13 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_delete_doublons_classes_desmfmc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoutFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_slug', models.CharField(help_text="Slug de la formation (ex: 'desmfmc', 'sante-communautaire')", max_length=100, unique=True, verbose_name='Identifiant de la formation')),
                ('nom_formation', models.CharField(help_text='Nom complet de la formation', max_length=200, verbose_name='Nom de la formation')),
                ('niveau', models.CharField(choices=[('diu', 'DIU (Diplôme Inter-Universitaire)'), ('licence', 'Licence'), ('master', 'Master'), ('annuel', 'Par année'), ('unique', 'Paiement unique')], default='unique', max_length=20, verbose_name='Niveau de formation')),
                ('cout_principal', models.DecimalField(decimal_places=0, default=0, help_text='Coût principal de la formation', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût principal (FCFA)')),
                ('cout_diu', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Coût pour le DIU (si applicable)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût DIU (FCFA)')),
                ('cout_licence', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Coût pour la Licence (si applicable)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût Licence (FCFA)')),
                ('cout_master', models.DecimalField(blank=True, decimal_places=0, default=0, help_text='Coût pour le Master (si applicable)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût Master (FCFA)')),
                ('modalite_paiement', models.CharField(choices=[('unique', 'Paiement en une seule tranche'), ('tranches', 'Paiement en plusieurs tranches'), ('annuel', 'Paiement annuel')], default='unique', max_length=20, verbose_name='Modalité de paiement')),
                ('conditions_paiement', models.TextField(blank=True, help_text="Conditions spécifiques de paiement (ex: avant le début de l'évaluation finale)", null=True, verbose_name='Conditions de paiement')),
                ('informations_supplementaires', models.TextField(blank=True, help_text='Informations complémentaires sur le coût et les modalités', null=True, verbose_name='Informations supplémentaires')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver pour masquer cette formation', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Coût de formation',
                'verbose_name_plural': 'Coûts des formations',
                'ordering': ['nom_formation'],
            },
        ),
    ]
