# Generated by Django 4.2.26 on 2025-11-13 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0018_coutformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtudiantMed6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text="Numéro de matricule de l'étudiant (2ème colonne du fichier Excel)", max_length=50, unique=True, verbose_name='Matricule')),
                ('prenom', models.CharField(help_text="Prénom de l'étudiant (3ème colonne du fichier Excel)", max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(help_text="Nom de l'étudiant (4ème colonne du fichier Excel)", max_length=100, verbose_name='Nom')),
                ('numero_carte_scolaire', models.CharField(blank=True, help_text='Numéro de la Carte Scolaire (si disponible)', max_length=100, null=True, verbose_name='Numéro de Carte Scolaire')),
                ('actif', models.BooleanField(default=True, help_text="Désactiver pour retirer l'accès gratuit", verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiant_med6', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur associé')),
            ],
            options={
                'verbose_name': 'Étudiant Médecine 6',
                'verbose_name_plural': 'Étudiants Médecine 6',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['matricule'], name='utilisateur_matricu_1b9d37_idx'), models.Index(fields=['nom', 'prenom'], name='utilisateur_nom_f89794_idx')],
            },
        ),
    ]
