# Generated by Django 4.2.26 on 2025-11-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0019_etudiantmed6'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeMed6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(help_text='Ex: 2024-2025', max_length=20, unique=True, verbose_name='Année universitaire')),
                ('date_cloture', models.DateField(help_text="Date de fin de l'année universitaire", verbose_name="Date de clôture de l'année universitaire")),
                ('date_import', models.DateTimeField(auto_now_add=True, verbose_name="Date d'import")),
                ('fichier_source', models.CharField(blank=True, help_text='Nom du fichier Excel importé', max_length=255, null=True, verbose_name='Fichier source')),
                ('active', models.BooleanField(default=True, help_text='Une seule liste peut être active à la fois', verbose_name='Liste active')),
                ('nombre_etudiants', models.IntegerField(default=0, verbose_name="Nombre d'étudiants")),
            ],
            options={
                'verbose_name': 'Liste Med 6',
                'verbose_name_plural': 'Listes Med 6',
                'ordering': ['-annee_universitaire'],
            },
        ),
        migrations.AlterField(
            model_name='etudiantmed6',
            name='matricule',
            field=models.CharField(help_text="Numéro de matricule de l'étudiant (2ème colonne du fichier Excel)", max_length=50, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='etudiantmed6',
            name='liste',
            field=models.ForeignKey(blank=True, help_text='Liste Med 6 à laquelle appartient cet étudiant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='utilisateurs.listemed6', verbose_name="Liste d'appartenance"),
        ),
        migrations.AlterUniqueTogether(
            name='etudiantmed6',
            unique_together={('liste', 'matricule')},
        ),
    ]
