# Generated by Django 4.2.25 on 2025-11-14 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0021_add_date_dispensation_and_alerte_lecon'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la lettre')),
                ('type_lettre', models.CharField(choices=[('information', 'Information générale'), ('annonce', 'Annonce importante'), ('rappel', 'Rappel'), ('convocation', 'Convocation'), ('resultat', 'Résultats'), ('autre', 'Autre')], default='information', max_length=20, verbose_name='Type de lettre')),
                ('contenu', models.TextField(verbose_name='Contenu de la lettre')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('envoye_par_email', models.BooleanField(default=False, verbose_name='Envoyé par email')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='lettres_information/', verbose_name='Pièce jointe')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Lettre d'information",
                'verbose_name_plural': "Lettres d'information",
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ModelePedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du modèle')),
                ('type_modele', models.CharField(choices=[('plan_cours', 'Plan de cours'), ('fiche_pedagogique', 'Fiche pédagogique'), ('grille_evaluation', "Grille d'évaluation"), ('template_presentation', 'Template de présentation'), ('guide_enseignant', 'Guide enseignant'), ('autre', 'Autre')], default='plan_cours', max_length=30, verbose_name='Type de modèle')),
                ('description', models.TextField(verbose_name='Description')),
                ('fichier', models.FileField(upload_to='modeles_pedagogiques/', verbose_name='Fichier')),
                ('visible_enseignants', models.BooleanField(default=True, verbose_name='Visible par les enseignants')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle pédagogique',
                'verbose_name_plural': 'Modèles pédagogiques',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SignatureCoordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_signataire', models.CharField(help_text='Nom complet de la personne autorisée à signer les documents', max_length=200, verbose_name='Nom du signataire')),
                ('titre_signataire', models.CharField(default='Coordonnateur DESMFMC', help_text='Titre ou fonction du signataire (ex: Coordonnateur DESMFMC)', max_length=200, verbose_name='Titre/Fonction')),
                ('cachet', models.ImageField(blank=True, help_text='Image du cachet officiel de la coordination', null=True, upload_to='signatures/', verbose_name='Cachet de la coordination')),
                ('actif', models.BooleanField(default=True, help_text='Utiliser cette signature pour les nouveaux documents', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Signature de la coordination',
                'verbose_name_plural': 'Signatures de la coordination',
                'ordering': ['-actif', '-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='etudiantmed6',
            index=models.Index(fields=['liste', 'actif'], name='utilisateur_liste_i_635d30_idx'),
        ),
        migrations.AddField(
            model_name='modelepedagogique',
            name='auteur',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'coordination'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_pedagogiques_crees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='lettreinformation',
            name='auteur',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur__in': ['enseignant', 'coordination']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettres_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='lettreinformation',
            name='classe_cible',
            field=models.ForeignKey(blank=True, help_text='Si spécifiée, la lettre sera envoyée à tous les étudiants de cette classe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lettres_information', to='utilisateurs.classe', verbose_name='Classe cible'),
        ),
        migrations.AddField(
            model_name='lettreinformation',
            name='destinataires',
            field=models.ManyToManyField(help_text='Sélectionner les étudiants destinataires. Laisser vide pour tous les étudiants.', limit_choices_to={'type_utilisateur': 'etudiant'}, related_name='lettres_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires'),
        ),
    ]
