# Generated by Django 4.2.25 on 2025-11-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0022_add_signature_coordination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signaturecoordination',
            options={'ordering': ['-est_directeur', '-actif', '-date_creation'], 'verbose_name': 'Signature de la coordination', 'verbose_name_plural': 'Signatures de la coordination'},
        ),
        migrations.AddField(
            model_name='signaturecoordination',
            name='est_directeur',
            field=models.BooleanField(default=False, help_text='Cocher si cette personne est le Directeur du Programme', verbose_name='Directeur du Programme'),
        ),
        migrations.AddField(
            model_name='signaturecoordination',
            name='prenom_signataire',
            field=models.CharField(blank=True, help_text='Prénom du signataire (optionnel, sera combiné avec le nom)', max_length=200, verbose_name='Prénom du signataire'),
        ),
        migrations.AlterField(
            model_name='signaturecoordination',
            name='titre_signataire',
            field=models.CharField(default='Coordonnateur DESMFMC', help_text='Titre ou fonction du signataire (ex: Directeur du Programme DESMFMC)', max_length=200, verbose_name='Titre/Fonction'),
        ),
    ]
