# Generated by Django 4.2.25 on 2025-11-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0023_update_signature_coordination'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='fichier_contenu',
            field=models.FileField(blank=True, help_text='Fichier PDF, Word, PowerPoint, etc. contenant le contenu du cours', null=True, upload_to='cours/fichiers/', verbose_name='Fichier du cours'),
        ),
    ]
