# Generated by Django 4.2.25 on 2025-11-15 01:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0024_add_fichier_contenu_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarnetStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2024-2025', max_length=20, verbose_name='Année scolaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Carnet actif')),
                ('etudiant', models.OneToOneField(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='carnet_stage', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Carnet de stage',
                'verbose_name_plural': 'Carnets de stage',
                'ordering': ['-annee_scolaire', 'etudiant__username'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCompetenceTableau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acquisition', models.IntegerField(blank=True, choices=[(1, '1 - Non acquis'), (2, "2 - En cours d'acquisition"), (3, '3 - Acquis'), (4, '4 - Maîtrisé')], null=True, verbose_name="Niveau d'acquisition")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date d'évaluation")),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_tableaux', to='utilisateurs.competence')),
            ],
            options={
                'verbose_name': 'Évaluation compétence dans tableau',
                'verbose_name_plural': 'Évaluations compétences dans tableaux',
            },
        ),
        migrations.CreateModel(
            name='TableauEvaluationClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Année du DES')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_evaluation', to='utilisateurs.carnetstage', verbose_name='Carnet de stage')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableaux_evaluation', to='utilisateurs.classe', verbose_name='Classe')),
                ('competences', models.ManyToManyField(related_name='tableaux_evaluation', through='utilisateurs.EvaluationCompetenceTableau', to='utilisateurs.competence', verbose_name='Compétences évaluées')),
                ('jalon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tableaux_evaluation', to='utilisateurs.jalonprogramme', verbose_name='Jalon associé')),
            ],
            options={
                'verbose_name': "Tableau d'évaluation par classe",
                'verbose_name_plural': "Tableaux d'évaluation par classe",
                'ordering': ['annee', 'classe__nom'],
                'unique_together': {('carnet', 'classe', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Année du DES (1-4)')),
                ('type_stage', models.CharField(choices=[('hospitalier_annee1', 'Stage hospitalier (Année 1)'), ('cscom_urbain', 'Stage CSCom-U urbain'), ('cscom_rural', 'Stage CSCom-U rural'), ('autre', 'Autre stage')], max_length=30, verbose_name='Type de stage')),
                ('lieu_stage', models.CharField(max_length=300, verbose_name='Lieu du stage')),
                ('service_stage', models.CharField(blank=True, max_length=200, verbose_name='Service / Département')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('duree_semaines', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée (en semaines)')),
                ('maitre_stage_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom du maître de stage (si non-enseignant)')),
                ('maitre_stage_titre', models.CharField(blank=True, max_length=100, verbose_name='Titre du maître de stage')),
                ('note_globale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note globale (sur 20)')),
                ('appreciation_globale', models.TextField(blank=True, verbose_name='Appréciation globale')),
                ('points_forts', models.TextField(blank=True, verbose_name='Points forts')),
                ('points_amelioration', models.TextField(blank=True, verbose_name='Points à améliorer')),
                ('valide', models.BooleanField(default=False, verbose_name='Stage validé')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('carnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_stages', to='utilisateurs.carnetstage', verbose_name='Carnet de stage')),
                ('maitre_stage', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_maitre', to=settings.AUTH_USER_MODEL, verbose_name='Maître de stage')),
                ('stage_annee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_carnet', to='utilisateurs.stagepremiereannee', verbose_name='Stage 1ère année (si applicable)')),
                ('stage_rotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_carnet', to='utilisateurs.stagerotationdes', verbose_name='Stage rotation DES (si applicable)')),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur__in': ['enseignant', 'coordination']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Évaluation de stage',
                'verbose_name_plural': 'Évaluations de stages',
                'ordering': ['annee', 'date_debut'],
            },
        ),
        migrations.AddField(
            model_name='evaluationcompetencetableau',
            name='tableau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_competences_tableau', to='utilisateurs.tableauevaluationclasse'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationcompetencetableau',
            unique_together={('tableau', 'competence')},
        ),
        migrations.CreateModel(
            name='EvaluationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acquisition', models.IntegerField(blank=True, choices=[(1, '1 - Non acquis'), (2, "2 - En cours d'acquisition"), (3, '3 - Acquis'), (4, '4 - Maîtrisé')], null=True, verbose_name="Niveau d'acquisition")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire sur la compétence')),
                ('observations', models.TextField(blank=True, verbose_name='Observations spécifiques')),
                ('evalue_par_maitre', models.BooleanField(default=False, verbose_name='Évalué par le maître de stage')),
                ('date_evaluation', models.DateField(blank=True, null=True, verbose_name="Date d'évaluation")),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_stages', to='utilisateurs.competence', verbose_name='Compétence')),
                ('evaluation_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_competences', to='utilisateurs.evaluationstage', verbose_name='Évaluation de stage')),
                ('jalon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_competences', to='utilisateurs.jalonprogramme', verbose_name='Jalon associé')),
            ],
            options={
                'verbose_name': 'Évaluation de compétence',
                'verbose_name_plural': 'Évaluations de compétences',
                'ordering': ['competence__libelle'],
                'unique_together': {('evaluation_stage', 'competence')},
            },
        ),
    ]
