# Generated by Django 4.2.25 on 2025-11-15 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0026_evaluationstage_date_evaluation_superviseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProclamationResultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(help_text='Ex: 2024-2025', max_length=20, verbose_name='Année scolaire')),
                ('date_proclamation', models.DateField(verbose_name='Date de proclamation des résultats')),
                ('actif', models.BooleanField(default=True, verbose_name='Proclamation active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proclamations_resultats', to='utilisateurs.classe', verbose_name='Classe')),
                ('proclame_par', models.ForeignKey(blank=True, limit_choices_to={'membre_coordination': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proclamations_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Proclamé par')),
            ],
            options={
                'verbose_name': 'Proclamation des résultats',
                'verbose_name_plural': 'Proclamations des résultats',
                'ordering': ['-date_proclamation', 'classe__nom'],
                'unique_together': {('classe', 'annee_scolaire')},
            },
        ),
    ]
