# Generated by Django 4.2.25 on 2025-11-15 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0027_proclamationresultats'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='deux_facteurs_actives',
            field=models.BooleanField(default=False, help_text='Active la vérification par code email pour les accès sensibles', verbose_name='Double authentification activée'),
        ),
        migrations.CreateModel(
            name='Code2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Code de vérification 2FA')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('expire_le', models.DateTimeField(verbose_name='Expire le')),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_2fa', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Code 2FA',
                'verbose_name_plural': 'Codes 2FA',
                'ordering': ['-cree_le'],
            },
        ),
    ]
