# Generated by Django 4.2.25 on 2025-11-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0028_utilisateur_deux_facteurs_actives_code2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='superviseur_cec',
            field=models.BooleanField(default=False, help_text='Accès aux évaluations de stages pour les superviseurs cliniques et CEC. Une personne peut être à la fois enseignant et superviseur/CEC.', verbose_name='Superviseur clinique / CEC'),
        ),
    ]
