# Generated by Django 4.2.25 on 2025-11-15 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0029_utilisateur_superviseur_cec'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='centre_supervision',
            field=models.ForeignKey(blank=True, help_text='Centre CSCom-U où ce superviseur/CEC est principalement assigné. Les évaluations seront automatiquement filtrées par ce centre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superviseurs', to='utilisateurs.cscomucentre', verbose_name='Centre de supervision principal'),
        ),
    ]
