# Generated by Django 4.2.26 on 2025-11-22 12:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0033_create_classes_desmfmc_attribuer_etudiants'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('mode_paiement', models.CharField(choices=[('bancaire', 'Bancaire'), ('espece', 'Espèce'), ('orange_money', 'Orange Money')], default='bancaire', max_length=20, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence du paiement (numéro de transaction, etc.)', max_length=100, null=True, verbose_name='Référence de paiement')),
                ('preuve_paiement', models.FileField(blank=True, help_text="Capture d'écran, reçu, etc.", null=True, upload_to='cours/preuves_paiement/', verbose_name='Preuve de paiement')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='utilisateurs.cours', verbose_name='Cours')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_cours', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_cours_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Paiement de cours',
                'verbose_name_plural': 'Paiements de cours',
                'ordering': ['-date_paiement'],
                'unique_together': {('cours', 'etudiant')},
            },
        ),
    ]
