# Generated by Django 4.2.26 on 2025-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0034_paiementcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='coutformation',
            name='bourse_offerte',
            field=models.BooleanField(default=False, help_text='Si une bourse est offerte, le coût sera doublé', verbose_name='Bourse offerte'),
        ),
    ]
