# Generated by Django 4.2.26 on 2025-11-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0036_rename_paiementcours_to_paiementformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coutformation',
            name='niveau',
            field=models.CharField(choices=[('diu', 'DIU (Diplôme Inter-Universitaire)'), ('du', 'DU (Diplôme Universitaire)'), ('licence', 'Licence'), ('master', 'Master'), ('annuel', 'Par année'), ('unique', 'Paiement unique')], default='unique', max_length=20, verbose_name='Niveau de formation'),
        ),
    ]
