# Generated by Django 4.2.26 on 2025-11-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0037_alter_coutformation_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cscomucentre',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exemple : 12.639947', max_digits=9, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='cscomucentre',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exemple : -7.984300', max_digits=9, null=True, verbose_name='Longitude GPS'),
        ),
    ]
