# Generated by Django 4.2.26 on 2025-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0038_cscomucentre_latitude_cscomucentre_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcompetencetableau',
            options={'ordering': ['tableau__classe__nom', 'tableau__annee', 'competence__libelle'], 'verbose_name': '📊 Évaluation de compétence (tableau par classe)', 'verbose_name_plural': '📊 Évaluations de compétences (tableaux par classe)'},
        ),
        migrations.AddField(
            model_name='competence',
            name='classes',
            field=models.ManyToManyField(blank=True, help_text='Classes où cette compétence est enseignée et évaluée', related_name='competences_classes', to='utilisateurs.classe', verbose_name='Classes associées'),
        ),
        migrations.AddField(
            model_name='competence',
            name='jalons',
            field=models.ManyToManyField(blank=True, help_text='Jalons du programme où cette compétence est évaluée', related_name='competences_jalons', to='utilisateurs.jalonprogramme', verbose_name='Jalons associés'),
        ),
    ]
