# Generated by Django 4.2.26 on 2025-11-29 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0042_update_echelle_competencejalon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Compte principal FMOS, Compte DESMFMC, etc.', max_length=200, verbose_name='Nom du compte')),
                ('nom_banque', models.CharField(max_length=200, verbose_name='Nom de la banque')),
                ('numero_compte', models.CharField(help_text='Numéro de compte bancaire', max_length=50, verbose_name='Numéro de compte')),
                ('iban', models.CharField(blank=True, help_text='Code IBAN du compte (optionnel)', max_length=34, null=True, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, help_text='Code SWIFT/BIC de la banque (optionnel)', max_length=11, null=True, verbose_name='SWIFT/BIC')),
                ('actif', models.BooleanField(default=True, help_text='Désactiver pour masquer ce compte dans les choix', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte bancaire',
                'verbose_name_plural': 'Comptes bancaires',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='paiementformation',
            name='compte_bancaire',
            field=models.ForeignKey(blank=True, help_text='Compte bancaire sur lequel le paiement a été effectué (si mode bancaire)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_formations', to='utilisateurs.comptebancaire', verbose_name='Compte bancaire'),
        ),
    ]
