# Generated by Django 4.2.26 on 2025-12-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0043_comptebancaire_paiementformation_compte_bancaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='classes_enseignees',
            field=models.ManyToManyField(blank=True, help_text='Classes où cet enseignant dispense des cours', related_name='enseignants', to='utilisateurs.classe', verbose_name='Classes enseignées'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='fichier_contenu',
            field=models.FileField(blank=True, help_text='⚠️ DÉPRÉCIÉ : Les fichiers doivent être téléversés au niveau des leçons, pas du cours. Ce champ est conservé pour compatibilité mais ne devrait plus être utilisé.', null=True, upload_to='cours/fichiers/', verbose_name='Fichier du cours (déprécié)'),
        ),
    ]
