# Generated by Django 4.2.26 on 2026-01-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0044_add_classes_enseignees_to_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='pref_verification',
            field=models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS')], default='email', max_length=10, verbose_name='Méthode de vérification préférée'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='deux_facteurs_actives',
            field=models.BooleanField(default=False, help_text='Active la vérification par code email ou SMS pour les accès sensibles', verbose_name='Double authentification activée'),
        ),
    ]
