# Generated by Django 4.2.26 on 2025-11-10 15:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateurs', '0003_classe_competence_cours_formation_jalonprogramme_and_more'),
        ('evaluations', '0003_accompagnement_evaluation_evaluationenseignant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationpratique',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_pratiques', to='utilisateurs.cours'),
        ),
        migrations.AddField(
            model_name='evaluationpratique',
            name='titre',
            field=models.CharField(default='Évaluation pratique', max_length=200),
        ),
        migrations.AddField(
            model_name='evaluationtheorique',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_theoriques', to='utilisateurs.cours'),
        ),
        migrations.AddField(
            model_name='evaluationtheorique',
            name='titre',
            field=models.CharField(default='Évaluation théorique', max_length=200),
        ),
        migrations.AddField(
            model_name='memoire',
            name='date_soumission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoire',
            name='date_soutenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='lieu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='evaluationpratique',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_pratiques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationpratique',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='evaluationtheorique',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_theoriques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluationtheorique',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='stage',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suiviindividuel',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis_individuels', to='utilisateurs.cours', verbose_name='Cours (optionnel)'),
        ),
        migrations.AddField(
            model_name='suiviindividuel',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='suivis_individuels', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='suiviindividuel',
            name='responsable',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_individuels_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='resultatevaluation',
            name='competences_demontrees',
            field=models.ManyToManyField(blank=True, related_name='resultats_competences', to='utilisateurs.competence', verbose_name='Compétences démontrées'),
        ),
        migrations.AddField(
            model_name='resultatevaluation',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='resultatevaluation',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='evaluations.evaluation', verbose_name='Évaluation'),
        ),
        migrations.AddField(
            model_name='resultatevaluation',
            name='objectifs_atteints',
            field=models.ManyToManyField(blank=True, related_name='resultats_objectifs', to='utilisateurs.objectifapprentissage', verbose_name='Objectifs atteints'),
        ),
        migrations.AddField(
            model_name='reponsepossible',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_possibles', to='evaluations.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='reponseetudiant',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='reponses_questions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='reponseetudiant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_etudiants', to='evaluations.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='reponseetudiant',
            name='reponses_choisies',
            field=models.ManyToManyField(blank=True, related_name='reponses_etudiants', to='evaluations.reponsepossible', verbose_name='Réponses choisies'),
        ),
        migrations.AddField(
            model_name='reponseetudiant',
            name='session_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_etudiants', to='utilisateurs.sessionevaluationenligne', verbose_name="Session d'évaluation"),
        ),
        migrations.AddField(
            model_name='rapportqualite',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_qualite_crees', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='rapportqualite',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_qualite', to='utilisateurs.classe', verbose_name='Classe (optionnel)'),
        ),
        migrations.AddField(
            model_name='rapportqualite',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_qualite', to='utilisateurs.formation', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='rapportqualite',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_qualite_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='question',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluation', verbose_name='Évaluation'),
        ),
        migrations.AddField(
            model_name='planamelioration',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_amelioration_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='planamelioration',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_amelioration', to='utilisateurs.formation', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='planamelioration',
            name='indicateurs_suivi',
            field=models.ManyToManyField(blank=True, related_name='plans_amelioration', to='evaluations.indicateurqualite', verbose_name='Indicateurs de suivi'),
        ),
        migrations.AddField(
            model_name='planamelioration',
            name='rapport_qualite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_amelioration', to='evaluations.rapportqualite', verbose_name='Rapport de qualité source'),
        ),
        migrations.AddField(
            model_name='planamelioration',
            name='responsables',
            field=models.ManyToManyField(limit_choices_to={'type_utilisateur': 'enseignant'}, related_name='plans_amelioration_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Responsables'),
        ),
        migrations.AddField(
            model_name='participationsession',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='participations_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='participationsession',
            name='session_evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='utilisateurs.sessionevaluationenligne', verbose_name="Session d'évaluation"),
        ),
        migrations.AddField(
            model_name='mesurequalite',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures_qualite', to='utilisateurs.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='mesurequalite',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures_qualite', to='utilisateurs.cours', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='mesurequalite',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesures_qualite', to='utilisateurs.formation', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='mesurequalite',
            name='indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='evaluations.indicateurqualite', verbose_name='Indicateur'),
        ),
        migrations.AddField(
            model_name='mesurequalite',
            name='mesure_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures_qualite_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Mesuré par'),
        ),
        migrations.AddField(
            model_name='evaluationformation',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_classe', to='utilisateurs.classe', verbose_name='Classe (optionnel)'),
        ),
        migrations.AddField(
            model_name='evaluationformation',
            name='evaluateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_formation_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur'),
        ),
        migrations.AddField(
            model_name='evaluationformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_formation', to='utilisateurs.formation', verbose_name='Formation'),
        ),
        migrations.AddField(
            model_name='evaluationenseignant',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_enseignants', to='utilisateurs.cours', verbose_name='Cours (optionnel)'),
        ),
        migrations.AddField(
            model_name='evaluationenseignant',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant'),
        ),
        migrations.AddField(
            model_name='evaluationenseignant',
            name='evaluateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_enseignants_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='competences_evaluees',
            field=models.ManyToManyField(blank=True, related_name='evaluations', to='utilisateurs.competence', verbose_name='Compétences évaluées'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='utilisateurs.cours', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='objectifs_evalues',
            field=models.ManyToManyField(blank=True, related_name='evaluations', to='utilisateurs.objectifapprentissage', verbose_name='Objectifs évalués'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='type_evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='evaluations.typeevaluation', verbose_name="Type d'évaluation"),
        ),
        migrations.AddField(
            model_name='accompagnement',
            name='accompagnateur',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompagnements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Accompagnateur'),
        ),
        migrations.AddField(
            model_name='accompagnement',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='accompagnements', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='resultatevaluation',
            unique_together={('evaluation', 'etudiant')},
        ),
        migrations.AlterUniqueTogether(
            name='reponseetudiant',
            unique_together={('session_evaluation', 'question', 'etudiant')},
        ),
        migrations.AlterUniqueTogether(
            name='participationsession',
            unique_together={('session_evaluation', 'etudiant')},
        ),
    ]
