# Generated by Django 4.2.25 on 2025-11-27 20:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateurs', '0040_competencejalon'),
        ('evaluations', '0004_evaluationpratique_cours_evaluationpratique_titre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CritereEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=500, verbose_name='Libellé du critère')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('poids', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids/Pondération')),
                ('note_maximale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note maximale (si différente de la grille)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteres_evaluation', to='utilisateurs.competence', verbose_name='Compétence associée')),
            ],
            options={
                'verbose_name': "Critère d'évaluation",
                'verbose_name_plural': "Critères d'évaluation",
                'ordering': ['grille', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ElementEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('libelle', models.CharField(max_length=500, verbose_name="Libellé de l'élément")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('poids', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids/Pondération')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='evaluations.critereevaluation', verbose_name='Critère parent')),
            ],
            options={
                'verbose_name': "Élément d'évaluation",
                'verbose_name_plural': "Éléments d'évaluation",
                'ordering': ['critere', 'ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationAvecGrille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note obtenue')),
                ('note_sur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note sur')),
                ('commentaires_generaux', models.TextField(blank=True, null=True, verbose_name='Commentaires généraux')),
                ('points_forts', models.TextField(blank=True, null=True, verbose_name='Points forts')),
                ('axes_amelioration', models.TextField(blank=True, null=True, verbose_name="Axes d'amélioration")),
                ('date_evaluation', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'évaluation")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_grilles', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant évalué')),
                ('evaluateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_realisees', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur')),
            ],
            options={
                'verbose_name': 'Évaluation avec grille',
                'verbose_name_plural': 'Évaluations avec grilles',
                'ordering': ['-date_evaluation', 'etudiant'],
            },
        ),
        migrations.CreateModel(
            name='ReponseCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note obtenue')),
                ('niveau', models.CharField(blank=True, choices=[('insuffisant', 'Insuffisant'), ('inconstant', 'Inconstant'), ('conforme', 'Conforme'), ('depasse', 'Dépasse les attentes'), ('na', 'N/A')], max_length=20, null=True, verbose_name='Niveau atteint')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.critereevaluation', verbose_name='Critère')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_criteres', to='evaluations.evaluationavecgrille', verbose_name='Évaluation')),
            ],
            options={
                'verbose_name': 'Réponse critère',
                'verbose_name_plural': 'Réponses critères',
                'unique_together': {('evaluation', 'critere')},
            },
        ),
        migrations.CreateModel(
            name='TypeGrilleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_grille', models.CharField(choices=[('formative', 'Évaluation Formative'), ('sommative', 'Évaluation Sommative'), ('finale', 'Évaluation Finale'), ('supervision', 'Supervision'), ('simulation', 'Activité de Simulation'), ('scenario', 'Activité de Scénario'), ('presentation', 'Présentation'), ('habiletes_cliniques', 'Habiletés Cliniques')], max_length=30, verbose_name='Type de grille')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type de grille d'évaluation",
                'verbose_name_plural': "Types de grilles d'évaluation",
                'ordering': ['type_grille', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='GrilleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre de la grille')),
                ('description', models.TextField(verbose_name='Description')),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note maximale')),
                ('echelle_evaluation', models.CharField(choices=[('1-4', '1 : Insuffisant · 2 : Inconstant · 3 : Conforme · 4 : Dépasse les attentes'), ('1-5', '1 : Insuffisant · 2 : Inconstant · 3 : Conforme · 4 : Dépasse · 5 : N/A'), ('0-20', 'Note sur 20'), ('0-100', 'Pourcentage (0-100)')], default='1-5', max_length=20, verbose_name="Échelle d'évaluation")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grilles_evaluation', to='utilisateurs.classe', verbose_name='Classe associée')),
                ('competences_evaluees', models.ManyToManyField(blank=True, related_name='grilles_evaluation', to='utilisateurs.competence', verbose_name='Compétences évaluées')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grilles_evaluation', to='utilisateurs.cours', verbose_name='Cours associé')),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grilles_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('jalons_evalues', models.ManyToManyField(blank=True, related_name='grilles_evaluation', to='utilisateurs.competencejalon', verbose_name='Jalons évalués')),
                ('type_grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles', to='evaluations.typegrilleevaluation', verbose_name='Type de grille')),
            ],
            options={
                'verbose_name': "Grille d'évaluation",
                'verbose_name_plural': "Grilles d'évaluation",
                'ordering': ['-date_creation', 'titre'],
            },
        ),
        migrations.AddField(
            model_name='evaluationavecgrille',
            name='grille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.grilleevaluation', verbose_name='Grille utilisée'),
        ),
        migrations.AddField(
            model_name='critereevaluation',
            name='grille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='evaluations.grilleevaluation', verbose_name="Grille d'évaluation"),
        ),
        migrations.AddField(
            model_name='critereevaluation',
            name='jalon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criteres_evaluation', to='utilisateurs.competencejalon', verbose_name='Jalon associé'),
        ),
        migrations.CreateModel(
            name='ReponseElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Note obtenue')),
                ('niveau', models.CharField(blank=True, choices=[('insuffisant', 'Insuffisant'), ('inconstant', 'Inconstant'), ('conforme', 'Conforme'), ('depasse', 'Dépasse les attentes'), ('na', 'N/A')], max_length=20, null=True, verbose_name='Niveau atteint')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.elementevaluation', verbose_name='Élément')),
                ('reponse_critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_elements', to='evaluations.reponsecritere', verbose_name='Réponse critère')),
            ],
            options={
                'verbose_name': 'Réponse élément',
                'verbose_name_plural': 'Réponses éléments',
                'unique_together': {('reponse_critere', 'element')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='evaluationavecgrille',
            unique_together={('grille', 'etudiant', 'date_evaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='critereevaluation',
            unique_together={('grille', 'ordre')},
        ),
    ]
