# Generated by Django 4.2.26 on 2025-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_add_evaluation_stage_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typegrilleevaluation',
            name='type_grille',
            field=models.CharField(choices=[('apprentissage', 'Apprentissage'), ('habiletes_cliniques', 'Habilités Cliniques'), ('formative', 'Évaluation Formative'), ('sommative', 'Évaluation Sommative'), ('finale', 'Évaluation Finale'), ('supervision', 'Supervision'), ('simulation', 'Activité de Simulation'), ('scenario', 'Activité de Scénario'), ('presentation', 'Présentation')], max_length=30, verbose_name='Type de grille'),
        ),
    ]
