# Generated by Django 4.2.26 on 2025-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_alter_typegrilleevaluation_type_grille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typegrilleevaluation',
            name='type_grille',
            field=models.CharField(choices=[('habiletes_cliniques', 'Habilités Cliniques (Apprentissage)'), ('formative', 'Évaluation Formative (Apprentissage)'), ('scenario', 'Scénario (Apprentissage)'), ('sommative', 'Évaluation Sommative'), ('finale', 'Évaluation Finale'), ('supervision', 'Supervision'), ('simulation', 'Activité de Simulation'), ('presentation', 'Présentation')], max_length=30, verbose_name='Type de grille'),
        ),
    ]
