# Generated by Django 4.2.26 on 2025-11-12 12:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0017_delete_doublons_classes_desmfmc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_decision', models.DateField(default=django.utils.timezone.now, verbose_name='Date de décision')),
                ('decision', models.CharField(choices=[('en_attente', 'En attente'), ('admis', 'Admis'), ('liste_attente', "Liste d'attente"), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Décision')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note finale (moyenne)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('confirmations_envoyees', models.BooleanField(default=False, verbose_name='Courriel de confirmation envoyé')),
            ],
            options={
                'verbose_name': "Décision d'admission",
                'verbose_name_plural': "Décisions d'admission",
                'ordering': ['-date_decision'],
            },
        ),
        migrations.CreateModel(
            name='DossierCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Identifiant interne du dossier (ex: DES-2025-001)', max_length=30, unique=True, verbose_name='Référence dossier')),
                ('date_depot', models.DateField(default=django.utils.timezone.now, verbose_name='Date de dépôt')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('incomplet', 'Incomplet'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='soumis', max_length=20, verbose_name='Statut du dossier')),
                ('observations', models.TextField(blank=True, verbose_name='Observations sur le dossier')),
                ('pieces_manquantes', models.TextField(blank=True, verbose_name='Pièces manquantes')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_candidature', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_candidature', to='utilisateurs.formation', verbose_name='Formation demandée')),
            ],
            options={
                'verbose_name': 'Dossier de candidature',
                'verbose_name_plural': 'Dossiers de candidature',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='EntretienIndividuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'entretien")),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Score sur 20')),
                ('seuil_reussite', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Seuil de réussite')),
                ('motivation', models.TextField(blank=True, verbose_name='Appréciation de la motivation')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entretien_individuel', to='admissions.dossiercandidature', verbose_name='Dossier de candidature')),
                ('evaluateur', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_realises', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur')),
            ],
            options={
                'verbose_name': 'Entretien individuel',
                'verbose_name_plural': 'Entretiens individuels',
                'ordering': ['-date_entretien'],
            },
        ),
        migrations.CreateModel(
            name='ExamenProbatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateField(default=django.utils.timezone.now, verbose_name="Date de l'examen probatoire")),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note sur 20')),
                ('seuil_reussite', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Seuil de réussite')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_probatoire', to='admissions.dossiercandidature', verbose_name='Dossier de candidature')),
            ],
            options={
                'verbose_name': 'Épreuve probatoire écrite',
                'verbose_name_plural': 'Épreuves probatoires écrites',
                'ordering': ['-date_examen'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee_coordination', 'Validée par la Coordination MFMC'), ('validee_decanat', 'Validée par le Décanat'), ('validee_complete', 'Validation complète (Coordination + Décanat)'), ('paiement_en_attente', 'Paiement en attente'), ('paiement_valide', 'Paiement validé'), ('inscription_complete', 'Inscription complète'), ('annulee', 'Annulée'), ('refusee', 'Refusée')], default='en_attente', max_length=30, verbose_name="Statut de l'inscription")),
                ('validee_par_coordination', models.BooleanField(default=False, verbose_name='Validée par la Coordination MFMC')),
                ('date_validation_coordination', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation Coordination MFMC')),
                ('validee_par_decanat', models.BooleanField(default=False, verbose_name='Validée par le Décanat')),
                ('date_validation_decanat', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation Décanat')),
                ('commentaires_validation', models.TextField(blank=True, null=True, verbose_name='Commentaires de validation')),
                ('montant_inscription', models.DecimalField(decimal_places=2, help_text="Montant à payer pour l'inscription", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Montant de l'inscription")),
                ('mode_paiement', models.CharField(blank=True, choices=[('liquide', 'Espèces (Secrétariat FMOS)'), ('carte_bancaire', 'Carte bancaire'), ('orange_money', 'Orange Money')], max_length=20, null=True, verbose_name='Mode de paiement')),
                ('paiement_valide', models.BooleanField(default=False, verbose_name='Paiement validé')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Numéro de transaction, référence Orange Money, etc.', max_length=100, null=True, verbose_name='Référence de paiement')),
                ('preuve_paiement', models.FileField(blank=True, help_text="Capture d'écran, reçu, etc.", null=True, upload_to='inscriptions/preuves_paiement/', verbose_name='Preuve de paiement')),
                ('date_validation_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation du paiement')),
                ('commentaires_paiement', models.TextField(blank=True, null=True, verbose_name='Commentaires sur le paiement')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('decision_admission', models.ForeignKey(blank=True, help_text="Lien vers la décision d'admission si disponible", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='admissions.decisionadmission', verbose_name="Décision d'admission")),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='admissions.dossiercandidature', verbose_name='Dossier de candidature')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='utilisateurs.formation', verbose_name='Formation')),
                ('validateur_coordination', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur__in': ['coordination', 'enseignant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees_coordination', to=settings.AUTH_USER_MODEL, verbose_name='Validateur Coordination MFMC')),
                ('validateur_decanat', models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur__in': ['coordination', 'enseignant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees_decanat', to=settings.AUTH_USER_MODEL, verbose_name='Validateur Décanat')),
                ('valideur_paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Personne ayant validé le paiement')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('dossier', 'formation')},
            },
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='evaluationattente',
            name='etudiant',
        ),
        migrations.DeleteModel(
            name='AdmissionEcrit',
        ),
        migrations.DeleteModel(
            name='Entretien',
        ),
        migrations.DeleteModel(
            name='EvaluationAttente',
        ),
        migrations.AddField(
            model_name='decisionadmission',
            name='dossier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_admission', to='admissions.dossiercandidature', verbose_name='Dossier de candidature'),
        ),
    ]
