# Generated by Django 4.2.26 on 2025-11-12 12:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_decisionadmission_dossiercandidature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('liquide', 'Espèces (Secrétariat FMOS)'), ('carte_bancaire', 'Carte bancaire'), ('orange_money', 'Orange Money')], help_text='Uniquement pour les formations certifiantes', max_length=20, null=True, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='montant_inscription',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Montant à payer pour l'inscription (uniquement pour les formations certifiantes)", max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Montant de l'inscription"),
        ),
    ]
