# Generated by Django 4.2.26 on 2025-11-24 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0004_alter_inscription_mode_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_formation', models.CharField(choices=[('DESMFMC', 'DESMFMC'), ('autre', 'Autre formation')], max_length=20, verbose_name='Type de formation')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('description', models.TextField(verbose_name='Description du document requis')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Document requis',
                'verbose_name_plural': 'Documents requis',
                'ordering': ['type_formation', 'ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='decisionadmission',
            name='date_envoi_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'email"),
        ),
        migrations.AddField(
            model_name='decisionadmission',
            name='email_confirmation_envoye',
            field=models.BooleanField(default=False, help_text="Indique si l'email de confirmation d'admission a été envoyé au candidat", verbose_name='Email de confirmation envoyé'),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='details_bourse',
            field=models.TextField(blank=True, help_text='Préciser les détails de la bourse si applicable', null=True, verbose_name='Détails de la bourse'),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='prise_en_charge_bourse',
            field=models.BooleanField(default=False, help_text='Préciser si les études sont prises en charge par une bourse', verbose_name='Études prises en charge par une bourse'),
        ),
        migrations.CreateModel(
            name='DocumentDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='dossiers_candidature/documents/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('valide', models.BooleanField(default=False, verbose_name='Document validé')),
                ('commentaire_validation', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('document_requis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_uploades', to='admissions.documentrequis', verbose_name='Document requis')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.dossiercandidature', verbose_name='Dossier de candidature')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Document du dossier',
                'verbose_name_plural': 'Documents des dossiers',
                'ordering': ['dossier', 'document_requis__ordre'],
                'unique_together': {('dossier', 'document_requis')},
            },
        ),
    ]
