# Generated by Django 4.2.26 on 2025-11-24 22:20

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilisateurs', '0037_alter_coutformation_niveau'),
        ('admissions', '0005_documentrequis_decisionadmission_date_envoi_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementAnneeDES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(help_text="Paiement pour l'accès à cette année", validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)], verbose_name='Année du DES (2, 3 ou 4)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Montant des frais d'inscription annuels")),
                ('mode_paiement', models.CharField(blank=True, choices=[('liquide', 'Espèces (Secrétariat FMOS)'), ('carte_bancaire', 'Carte bancaire'), ('orange_money', 'Orange Money')], max_length=20, null=True, verbose_name='Mode de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paiement_effectue', 'Paiement effectué'), ('paiement_valide', 'Paiement validé'), ('refuse', 'Refusé')], default='en_attente', max_length=30, verbose_name='Statut du paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='Numéro de transaction, référence Orange Money, etc.', max_length=100, null=True, verbose_name='Référence de paiement')),
                ('preuve_paiement', models.FileField(blank=True, help_text="Capture d'écran, reçu, etc.", null=True, upload_to='paiements_annee_des/preuves/', verbose_name='Preuve de paiement')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaires', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('etudiant', models.ForeignKey(limit_choices_to={'type_utilisateur': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_annee_des', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_annee_des', to='utilisateurs.formation', verbose_name='Formation')),
                ('resultat_annee', models.ForeignKey(blank=True, help_text="Résultat de l'année précédente (année-1) qui doit être validé", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='utilisateurs.resultatanneedes', verbose_name="Résultat de l'année précédente")),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_annee_des_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement annuel DES',
                'verbose_name_plural': 'Paiements annuels DES',
                'ordering': ['-date_creation'],
                'unique_together': {('etudiant', 'formation', 'annee')},
            },
        ),
    ]
