# Generated by Django 4.2.26 on 2025-11-25 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0006_paiementanneedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiercandidature',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='nom_candidat',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nom du candidat (si non connecté)'),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='prenom_candidat',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom du candidat (si non connecté)'),
        ),
        migrations.AddField(
            model_name='dossiercandidature',
            name='telephone_contact',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone de contact'),
        ),
        migrations.AlterField(
            model_name='documentrequis',
            name='type_formation',
            field=models.CharField(choices=[('DESMFMC', 'DESMFMC'), ('SANTE_COMMUNAUTAIRE', 'Santé communautaire'), ('autre', 'Autre formation')], max_length=20, verbose_name='Type de formation'),
        ),
        migrations.AlterField(
            model_name='dossiercandidature',
            name='candidat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_candidature', to=settings.AUTH_USER_MODEL, verbose_name='Candidat'),
        ),
    ]
