# Generated by Django 5.2.7 on 2025-11-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('echeance', models.DateField()),
                ('realisee', models.BooleanField(default=False)),
            ],
        ),
    ]
